# num_entries=sum([length(leaf_nodes[1].node2node_Z_matrices[1])
# length(leaf_nodes[1].node2node_Z_matrices[2][1])
# length(leaf_nodes[1].node2node_Z_matrices[2][2])
# length(leaf_nodes[1].node2node_Z_matrices[3])
# length(leaf_nodes[1].node2node_Z_matrices[4][1])
# length(leaf_nodes[1].node2node_Z_matrices[4][2])
# length(leaf_nodes[2].node2node_Z_matrices[1][1])
# length(leaf_nodes[2].node2node_Z_matrices[1][2])
# length(leaf_nodes[2].node2node_Z_matrices[2])
# length(leaf_nodes[2].node2node_Z_matrices[3][1])
# length(leaf_nodes[2].node2node_Z_matrices[3][2])
# length(leaf_nodes[2].node2node_Z_matrices[4])
# length(leaf_nodes[3].node2node_Z_matrices[1])
# length(leaf_nodes[3].node2node_Z_matrices[2][1])
# length(leaf_nodes[3].node2node_Z_matrices[2][2])
# length(leaf_nodes[3].node2node_Z_matrices[3])
# length(leaf_nodes[3].node2node_Z_matrices[4][1])
# length(leaf_nodes[3].node2node_Z_matrices[4][2])
# length(leaf_nodes[4].node2node_Z_matrices[1][1])
# length(leaf_nodes[4].node2node_Z_matrices[1][2])
# length(leaf_nodes[4].node2node_Z_matrices[2])
# length(leaf_nodes[4].node2node_Z_matrices[3][1])
# length(leaf_nodes[4].node2node_Z_matrices[3][2])
# length(leaf_nodes[4].node2node_Z_matrices[4])])
#
# total_rank=sum([size(leaf_nodes[1].node2node_Z_matrices[2][1],2)
# size(leaf_nodes[1].node2node_Z_matrices[4][1],2)
# size(leaf_nodes[2].node2node_Z_matrices[1][1],2)
# size(leaf_nodes[2].node2node_Z_matrices[3][1],2)
# size(leaf_nodes[3].node2node_Z_matrices[2][1],2)
# size(leaf_nodes[3].node2node_Z_matrices[4][1],2)
# size(leaf_nodes[4].node2node_Z_matrices[1][1],2)
# size(leaf_nodes[4].node2node_Z_matrices[3][1],2)])

leaf_nodes = octree.nodes[octree.leaf_node_idxs]
total = 0
for i=1:4
    global total
    total += length(leaf_nodes[i].element_idxs)
    println(length(leaf_nodes[i].element_idxs))
end
